export const LOAD_REPO_DETAILS_REQUEST = 'LOAD_REPO_DETAILS_REQUEST';
export const LOAD_REPO_DETAILS_SUCCESS = 'LOAD_REPO_DETAILS_SUCCESS';
export const LOAD_REPO_DETAILS_FAILURE = 'LOAD_REPO_DETAILS_FAILURE';

export const LOAD_REPOS_REQUEST = 'LOAD_REPOS_REQUEST';
export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_FAILURE = 'LOAD_REPOS_FAILURE';
